---
- name: Copy data to new disk
  ansible.builtin.command:
    argv:
      - cp
      - -a
      - "{{ old_mount_point }}/."
      - "{{ new_mount_point }}/"
  register: copy_result
  changed_when: copy_result.rc == 0